/* =========================================================================
   Drawing the pages ourselves
   -------------------------------------------------------------------------
   The obvious way to preview a PDF is an <iframe> pointed at a blob URL and
   letting the browser's built-in viewer do the work. It was rejected for two
   reasons, one proven and one likely.

   Proven: it cannot be verified. Playwright's Chromium is built without the
   PDF plugin, so every frame rendered as a black rectangle here — headless
   and headed alike. Shipping a preview screen nobody had ever seen working
   is exactly the class of mistake this project keeps finding.

   Likely: a corporate Windows image can turn that plugin off. Chrome and
   Edge both honour AlwaysOpenPdfExternally, and where it is set an <iframe>
   of a PDF downloads the file instead of showing it — the preview would be
   an empty box on the machines that matter most.

   pdf.js renders to a canvas with no plugin involved, so the preview looks
   the same on every machine and can be checked in a test. The worker is
   bundled from node_modules, not fetched from a CDN: this app runs on a
   laboratory network that may have no route to the internet at all.
   ========================================================================= */

import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';

/* Loaded on first preview, not at start-up. pdf.js is around a third of a
   megabyte before its worker, and most sessions never open a preview at all —
   on a workspace served from a share drive that is a third of a megabyte
   crossing SMB for nothing. */
let library: Promise<typeof import('pdfjs-dist')> | null = null;
function pdfjsLibrary() {
  if (!library) {
    library = import('pdfjs-dist').then((module) => {
      module.GlobalWorkerOptions.workerSrc = workerUrl;
      return module;
    });
  }
  return library;
}

export type RenderedPage = { pageNumber: number; width: number; height: number; url: string };

/**
 * Renders every page of one document to a PNG data URL.
 *
 * `scale` trades sharpness for memory, and both sides of that trade are now
 * measured rather than guessed.
 *
 * Sharpness: the reader is checking worksheet numbers before committing a
 * controlled document to paper, so soft is the wrong way for this to fail.
 * The floor is 2 — deliberately above the fleet's 1.25 device pixel ratio,
 * because a page rendered at 2 and drawn at 1 is downsampled and crisp, while
 * one rendered at 1.25 is not.
 *
 * Memory: 12 worksheets at scale 2 rendered 24 pages for about 17 MB of JS
 * heap, so roughly 0.7 MB a page. A forty-worksheet batch is therefore on the
 * order of 60 MB against the 16 GB these machines have. That is why there is
 * no page-eviction scheme here: it would buy nothing and cost a re-render
 * every time somebody scrolled back up to re-check a sheet.
 *
 * Pinned to pdfjs-dist 4.x. The original reason was a guess that turned out
 * to be wrong: version 6 calls `Map.prototype.getOrInsertComputed`, it threw
 * outright in testing, and a corporate Windows image seemed exactly where an
 * old browser would be sitting. The fleet was then measured and runs **Edge
 * 152**, which is current — so the constraint that justified the pin does not
 * apply here.
 *
 * It stays pinned anyway, as a choice rather than a necessity. 4.x is the
 * version this preview was built and verified against, the PDFs it renders
 * are generated by the server on the same machine rather than fetched from
 * anywhere, and there is no feature in 6.x this needs. Upgrade when there is
 * a reason to, and re-run the print preview end to end when doing so.
 */
export function previewScale() {
  if (typeof window === 'undefined') return 2;
  return Math.min(2.5, Math.max(2, window.devicePixelRatio || 1));
}

export async function renderPages(bytes: ArrayBuffer, scale = previewScale()): Promise<RenderedPage[]> {
  /* pdf.js takes ownership of the buffer it is given and detaches it. The
     same bytes are merged later, so it must have a copy of its own. */
  const pdfjs = await pdfjsLibrary();
  const own = bytes.slice(0);
  const task = pdfjs.getDocument({ data: new Uint8Array(own) });
  const document_ = await task.promise;
  const pages: RenderedPage[] = [];
  try {
    for (let number = 1; number <= document_.numPages; number += 1) {
      const page = await document_.getPage(number);
      const viewport = page.getViewport({ scale });
      const canvas = window.document.createElement('canvas');
      canvas.width = Math.ceil(viewport.width);
      canvas.height = Math.ceil(viewport.height);
      const context = canvas.getContext('2d');
      if (!context) break;
      await page.render({ canvasContext: context, viewport }).promise;
      pages.push({
        pageNumber: number,
        width: canvas.width,
        height: canvas.height,
        url: canvas.toDataURL('image/png')
      });
      page.cleanup();
    }
  } finally {
    /* Tears down the worker for this document; the loading task owns it. */
    await task.destroy();
  }
  return pages;
}
